version: '3.9'

services:
  db:
    build: ./mymongo
    container_name: go-mongo-container
    ports:
      - "27017:27017"
    networks:
      - my-network

  redis:
    build: ./redis-docker
    container_name: go-redis-container
    ports:
      - "6379:6379"
    networks:
      - my-network

  go-web-server-1:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: go-web-server-container-1
    environment:
      - PORT=3000
    ports:
      - "3001:3000"
    networks:
      - my-network

  go-web-server-2:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: go-web-server-container-2
    environment:
      - PORT=3000
    ports:
      - "3002:3000"
    networks:
      - my-network

  nginx:
    build: ./nginx-load-balancer
    container_name: go-nginx-container
    ports:
      - "80:80"
    networks:
      - my-network

  zookeeper:
    build: ./kafka-docker/zookeeper
    container_name: go-zookeeper-container
    ports:
      - "2181:2181"
    networks:
      - my-network
  
  kafka:
    build: ./kafka-docker/kafkaService
    container_name: go-kafka-container
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - my-network


networks:
  my-network:
    driver: bridge
